### ISSUE TITLE
Scrum Update 5: July 29th

### ISSUE THREAD

**Issue by NLmeng** [cpsc455-bugstorm/TravelersTea#203]
**_Due: July 30th Sunday 2023 10pm_**

For all team members:

1. What did you work on this past iteration (2 weeks)?
2. What were any major issues/challenges you ran into?
3. What do you plan to work on for this coming iteration (2 weeks)?

~5 sentences max

**Comment by vee-16** [comment]
Vaishnavi Sinha
CSID: h7b3p

What did you work on this past iteration (2 weeks)?

- FE/BE added ratings for places, fixing populate db script
- code reviews 

What were any major issues/challenges you ran into?

- Finding hidden errors in backend implementations

What do you plan to work on for this coming iteration (2 weeks)?

- Wrapping up project
- Ensuring to cross check remaining requirements with project rubric

**Comment by Graywing13** [comment]
Noreen Chan
CSID: s4v2b

What did you work on this past iteration (2 weeks)?

- Create compact view & mobile view
- Add pins per stage (instead of per city) & fix some colour-assigning issues
- Error handling bug fixes: make `generateTrip` return object & throw errors, getting stuck on brew screen

What were any major issues/challenges you ran into?

- Couldn't figure out map zooming since theres so much math >.< so meng took over for this one :)
- The project is more fun than doing Assignment 5, so I just didn't really do the latter. Deploying is not a light assignment...

What do you plan to work on for this coming iteration (2 weeks)?

- Add light mode 
- Plan presentation
- UI styling fixes e.g. ugly popovers

**Comment by NLmeng** [comment]
Lymeng Naret
CSID: o2l3k

What did you work on this past iteration (2 weeks)?

- implemented Colloquial Prompts and Extra Notes for Trips
- implemented alert for error/warning and fix some bugs
- deploy

What were any major issues/challenges you ran into?

- finding center of coordinates: converting latitude and longitude to cartesian coordinates, averaging them, and converting back to spherical coordinates.

What do you plan to work on for this coming iteration (2 weeks)?

- more bug fixes and polish up

**Comment by AndyLiang1** [comment]
Andy Liang
CSID: b4e3b

What did you work on this past iteration (2 weeks)?

Auth, schema design for future share itinerary function, postman test suite. 

What were any major issues/challenges you ran into?

Creating mock test for update stages was difficult because of the complex request body. But it was mostly tedious. 

What do you plan to work on for this coming iteration (2 weeks)?

Bug fixes, share itinerary code review and tests

**Comment by L0Lmaker** [comment]
Rithin Kumar Revur Suresh Kumar 
CSID: m2i4v
What did you work on this past iteration (2 weeks)?

Added Share itenenary feature

code reviews

What were any major issues/challenges you ran into?

Trying to work with existing logic for a new feature

What do you plan to work on for this coming iteration (2 weeks)?

Wrapping up project

Ensuring to cross check remaining requirements with project rubric
