### ISSUE TITLE
Is it possible to move eslintrc and prettier files to root?

### ISSUE THREAD

**Issue by L0Lmaker** [cpsc455-bugstorm/TravelersTea#31]
Instead of having 2 separate ones.

**Comment by L0Lmaker** [comment]
@NLmeng can you take a look at this

**Comment by L0Lmaker** [comment]
Have assigned #32 to you as well so you can enable CI after you finish with this issue

**Comment by NLmeng** [comment]
reasons i did not move eslintrc and prettier files to root:
- the project will need to have 3 package.json instead of 2, eslint and prettier needs to be on the same level as a package.json
- the 2 eslint configuration has some similarities, but not entirely. one is for a browser+react environment and the other is for a nodejs environment.

It is possible to combine them into root and let it cascade to all the files under root, if it is alright for everyone that we need to do 3 yarn installs instead of 2 and that we only use prettier (no specific lint for react, nodejs, etc.). in other words only check for these and nothing else `{
  "semi": false,
  "trailingComma": "all",
  "singleQuote": true,
  "printWidth": 80,
  "tabWidth": 2
}
`

**Comment by L0Lmaker** [comment]
LGTM
